### ISSUE TITLE
Docker Errors

### ISSUE THREAD

**Issue by aarande** [AndrewTBurks/jupyterlab_sage2#3]
I ran the Docker commands as listed and when I go to the page it works but does not render correctly and I have no SAGE2 options or menus. Here are the errors I am seeing from Chrome console. Any ideas? Thanks!

Navigated to http://198.215.7.232:8888/lab?token=ddf0fbd74c6dfa6a119ab05e86a4fee9f0854e8b57a7ebb6
react-dom.development.js:17210 Download the React DevTools for a better development experience: https://fb.me/react-devtools
index.out.js:1014 Error: Cannot find module "jupyterlab_sage2/"
    at webpackMissingModule (index.out.js:989)
    at main (index.out.js:989)
main @ index.out.js:1014
index.js:267 Plugin 'jupyter.themes.dark' failed to activate.
(anonymous) @ index.js:267
Promise rejected (async)
(anonymous) @ index.js:266
Application.start @ index.js:265
main @ index.out.js:1029
index.js:268 Error: No provider for: @jupyterlab/apputils:IThemeManager.
    at JupyterLab.Application.resolveRequiredService (index.js:182)
    at index.js:140
    at Array.map (<anonymous>)
    at JupyterLab.Application.activatePlugin (index.js:140)
    at index.js:266
    at Array.map (<anonymous>)
    at JupyterLab.Application.start (index.js:265)
    at main (index.out.js:1029)
(anonymous) @ index.js:268
Promise rejected (async)
(anonymous) @ index.js:266
Application.start @ index.js:265
main @ index.out.js:1029
index.js:267 Plugin 'jupyter.themes.light' failed to activate.
(anonymous) @ index.js:267
Promise rejected (async)
(anonymous) @ index.js:266
Application.start @ index.js:265
main @ index.out.js:1029
index.js:268 Error: No provider for: @jupyterlab/apputils:IThemeManager.
    at JupyterLab.Application.resolveRequiredService (index.js:182)
    at index.js:140
    at Array.map (<anonymous>)
    at JupyterLab.Application.activatePlugin (index.js:140)
    at index.js:266
    at Array.map (<anonymous>)
    at JupyterLab.Application.start (index.js:265)
    at main (index.out.js:1029)

**Comment by AndrewTBurks** [comment]
I tried to rebuild the image and pushed the new image to Docker hub. Does using the tag `latest` make a difference?

I think the UI issue was something from a certain version of JupyterLab, and it should be fixed now.

```
docker run -it --rm -p 8888:8888 sage2/jupyterlab-datascience-notebook:latest start.sh jupyter lab
```

Thank you for bringing up this issue -- let me know if this works.

**Comment by aarande** [comment]
It looks much better...the one thing I still don't see is a SAGE2 menu or anything to do with SAGE2.

**Comment by AndrewTBurks** [comment]
Can you provide me some information about your OS, Browser & version, Docker version, and the Docker Image ID from `docker images`?

**Comment by AndrewTBurks** [comment]
@aarande It seems to be fixed now. I did a fresh pull on a new system and the image worked. Sorry it took a bit to fix -- JupyterLab updated and moved the VirtualDom implementation from Phosphor to React so I had to rewrite a bit of the plugin.

If there are any more problems, please let me know. Sorry for any inconvenience!
